name: Build and Release Package

on:
  push:
    tags:
      - 'v*' # This will trigger the workflow when you push a tag that starts with 'v'
  workflow_dispatch: # Keep manual trigger for testing

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Build Docker image
      run: docker build -t mpxjc:latest .
      
    - name: Extract tarball from Docker container
      run: |
        container_id=$(docker run -d mpxjc:latest tail -f /dev/null)
        echo "Container started with ID: ${container_id}"
        sleep 2
        mkdir -p ./dist
        docker cp ${container_id}:/project/mpxj-node-1.0.0.tgz ./dist/
        echo "Copied tarball to ./dist/"
        docker stop ${container_id}
        docker rm ${container_id}
        echo "Container removed"
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/mpxj-node-1.0.0.tgz
        name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
